repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint
        args: [--fix]
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.31.0
    hooks:
      - id: djlint-django
        args: [--reformat]
