site_name: pydev-guide
repo_url: https://github.com/pydev-guide/pydev-guide.github.io
repo_name: pydev-guide
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tutorial:
      - tutorial/index.md
      - tutorial/bare_minimum.md
      - tutorial/project_metadata.md
      - tutorial/code_quality.md
      - tutorial/github.md
      - tutorial/publishing.md
  - Guides:
      - guides/index.md
      - pyproject.toml: guides/pyproject.md
      - Packaging: guides/packaging.md
      - Typing: guides/typing.md
      - Linters: guides/linters.md
      - IDEs: guides/ides.md
      - Formatters: guides/formatters.md
      - Testing: guides/testing.md
      - Version Management: guides/versioning.md
      - Publishing: guides/publishing.md
      - Continuous Integration: guides/ci.md
      - Documentation: guides/documentation.md
      - Publishing: guides/publishing.md
      - Pre-commit: guides/pre-commit.md
      - Dependency Management: guides/dependencies.md
  - Glossary: glossary.md
  - "[md demo]": demo.md

theme:
  name: material
  logo: img/flask_logo.svg
  favicon: img/flask_logo.svg
  font: false
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - navigation.footer
    # - navigation.instant  # hard to use with javascript on page load
    # - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - navigation.icons

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.progressbar:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: pydev-guide/pydev-guide.github.io
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - stylesheets/extra.css
        - stylesheets/termynal.css
      js_files:
        - javascripts/extra.js
        - javascripts/termynal.js
  - spellcheck:
      backends: # the backends you want to use
        - codespell: # or nested configs
            dictionaries: [clear, rare]

watch:
  - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pydev-guide/pydev-guide.github.io
  generator: false # footer attribution ... sorry :(
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!<br>Help us improve this page by
            <a href="https://github.com/pydev-guide/pydev-guide.github.io/issues/new/?title=[Feedback]+{title}+-+{url}"
            target="_blank" rel="noopener">opening an issue</a>,
            or click "Edit this page" in the sidebar to contribute.

extra_css:
  - stylesheets/termynal.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/termynal.js
  - javascripts/extra.js
